version: '3.1'

services:
  db:
    image: postgres
    container_name: arendera_postgres
    restart: always
    volumes:
      - ~/.pg/pg-data:/home/postgres/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: db01
      PGDATA: /home/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"